import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:flutter_inappwebview_example/models/setting_definition.dart';

/// Get all setting definitions organized by category.
Map<String, List<SettingDefinition>> getSettingDefinitions() {
  return {
    'General': [
      SettingDefinition(
        key: 'javaScriptEnabled',
        name: 'JavaScript Enabled',
        description: 'Enable JavaScript execution in the WebView',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.javaScriptEnabled,
      ),
      SettingDefinition(
        key: 'userAgent',
        name: 'User Agent',
        description: 'Custom user-agent string for the WebView',
        type: SettingType.string,
        defaultValue: '',
        property: InAppWebViewSettingsProperty.userAgent,
      ),
      SettingDefinition(
        key: 'applicationNameForUserAgent',
        name: 'Application Name for User Agent',
        description: 'Append to the existing user-agent',
        type: SettingType.string,
        defaultValue: '',
        property: InAppWebViewSettingsProperty.applicationNameForUserAgent,
      ),
      SettingDefinition(
        key: 'cacheEnabled',
        name: 'Cache Enabled',
        description: 'Enable browser caching',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.cacheEnabled,
      ),
      SettingDefinition(
        key: 'incognito',
        name: 'Incognito Mode',
        description: 'Open browser in incognito/private mode',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.incognito,
      ),
      SettingDefinition(
        key: 'supportZoom',
        name: 'Support Zoom',
        description: 'Enable zoom gestures and controls',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.supportZoom,
      ),
    ],
    'Layout': [
      SettingDefinition(
        key: 'useWideViewPort',
        name: 'Use Wide ViewPort',
        description: 'Enable support for HTML viewport meta tag',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.useWideViewPort,
      ),
      SettingDefinition(
        key: 'loadWithOverviewMode',
        name: 'Load With Overview Mode',
        description: 'Zoom out content to fit on screen',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.loadWithOverviewMode,
      ),
      SettingDefinition(
        key: 'minimumFontSize',
        name: 'Minimum Font Size',
        description: 'Minimum font size in pixels',
        type: SettingType.integer,
        defaultValue: 8,
        property: InAppWebViewSettingsProperty.minimumFontSize,
      ),
      SettingDefinition(
        key: 'defaultFontSize',
        name: 'Default Font Size',
        description: 'Default font size in pixels',
        type: SettingType.integer,
        defaultValue: 16,
        property: InAppWebViewSettingsProperty.defaultFontSize,
      ),
      SettingDefinition(
        key: 'defaultTextEncodingName',
        name: 'Default Text Encoding',
        description: 'Default text encoding for HTML pages',
        type: SettingType.string,
        defaultValue: 'UTF-8',
        property: InAppWebViewSettingsProperty.defaultTextEncodingName,
      ),
    ],
    'Content': [
      SettingDefinition(
        key: 'allowContentAccess',
        name: 'Allow Content Access',
        description: 'Enable content URL access',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.allowContentAccess,
      ),
      SettingDefinition(
        key: 'allowFileAccess',
        name: 'Allow File Access',
        description: 'Enable file system access',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.allowFileAccess,
      ),
      SettingDefinition(
        key: 'allowFileAccessFromFileURLs',
        name: 'Allow File Access From File URLs',
        description: 'Allow file:// URLs to access other file:// URLs',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.allowFileAccessFromFileURLs,
      ),
      SettingDefinition(
        key: 'allowUniversalAccessFromFileURLs',
        name: 'Allow Universal Access From File URLs',
        description: 'Allow file:// URLs to access any origin',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.allowUniversalAccessFromFileURLs,
      ),
      SettingDefinition(
        key: 'blockNetworkImage',
        name: 'Block Network Images',
        description: 'Block loading images from the network',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.blockNetworkImage,
      ),
      SettingDefinition(
        key: 'blockNetworkLoads',
        name: 'Block Network Loads',
        description: 'Block all network resource loading',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.blockNetworkLoads,
      ),
    ],
    'Media': [
      SettingDefinition(
        key: 'mediaPlaybackRequiresUserGesture',
        name: 'Media Requires User Gesture',
        description: 'Require user interaction to play media',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.mediaPlaybackRequiresUserGesture,
      ),
      SettingDefinition(
        key: 'allowsInlineMediaPlayback',
        name: 'Allows Inline Media Playback',
        description: 'Allow HTML5 media to play inline',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.allowsInlineMediaPlayback,
      ),
      SettingDefinition(
        key: 'allowsAirPlayForMediaPlayback',
        name: 'Allows AirPlay',
        description: 'Allow AirPlay for media playback',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.allowsAirPlayForMediaPlayback,
      ),
      SettingDefinition(
        key: 'allowsPictureInPictureMediaPlayback',
        name: 'Allows Picture-in-Picture',
        description: 'Allow videos to play in picture-in-picture',
        type: SettingType.boolean,
        defaultValue: true,
        property:
            InAppWebViewSettingsProperty.allowsPictureInPictureMediaPlayback,
      ),
      SettingDefinition(
        key: 'automaticallyAdjustsScrollIndicatorInsets',
        name: 'Auto Adjust Scroll Indicator Insets',
        description: 'Automatically adjust scroll indicator insets',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty
            .automaticallyAdjustsScrollIndicatorInsets,
      ),
    ],
    'JavaScript': [
      SettingDefinition(
        key: 'javaScriptCanOpenWindowsAutomatically',
        name: 'JS Can Open Windows',
        description: 'Allow JavaScript to open windows automatically',
        type: SettingType.boolean,
        defaultValue: false,
        property:
            InAppWebViewSettingsProperty.javaScriptCanOpenWindowsAutomatically,
      ),
      SettingDefinition(
        key: 'javaScriptBridgeEnabled',
        name: 'JavaScript Bridge Enabled',
        description: 'Enable the JavaScript bridge',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.javaScriptBridgeEnabled,
      ),
      SettingDefinition(
        key: 'javaScriptBridgeForMainFrameOnly',
        name: 'JS Bridge Main Frame Only',
        description: 'Restrict JavaScript bridge to main frame',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.javaScriptBridgeForMainFrameOnly,
      ),
    ],
    'Security': [
      SettingDefinition(
        key: 'mixedContentMode',
        name: 'Mixed Content Mode',
        description: 'How to handle mixed HTTP/HTTPS content',
        type: SettingType.enumeration,
        defaultValue: null,
        enumValues: {
          'Always Allow': MixedContentMode.MIXED_CONTENT_ALWAYS_ALLOW
              .toNativeValue(),
          'Never Allow': MixedContentMode.MIXED_CONTENT_NEVER_ALLOW
              .toNativeValue(),
          'Compatibility Mode': MixedContentMode
              .MIXED_CONTENT_COMPATIBILITY_MODE
              .toNativeValue(),
        },
        property: InAppWebViewSettingsProperty.mixedContentMode,
      ),
      SettingDefinition(
        key: 'useShouldInterceptRequest',
        name: 'Use Should Intercept Request',
        description: 'Enable request interception events',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.useShouldInterceptRequest,
      ),
      SettingDefinition(
        key: 'useShouldOverrideUrlLoading',
        name: 'Use Should Override URL Loading',
        description: 'Enable URL loading override events',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.useShouldOverrideUrlLoading,
      ),
      SettingDefinition(
        key: 'useOnLoadResource',
        name: 'Use On Load Resource',
        description: 'Enable resource loading events',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.useOnLoadResource,
      ),
      SettingDefinition(
        key: 'isFraudulentWebsiteWarningEnabled',
        name: 'Fraudulent Website Warning',
        description: 'Show warnings for suspected phishing/malware',
        type: SettingType.boolean,
        defaultValue: true,
        property:
            InAppWebViewSettingsProperty.isFraudulentWebsiteWarningEnabled,
      ),
      SettingDefinition(
        key: 'safeBrowsingEnabled',
        name: 'Safe Browsing',
        description: 'Enable Google Safe Browsing',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.safeBrowsingEnabled,
      ),
    ],
    'Cache': [
      SettingDefinition(
        key: 'cacheMode',
        name: 'Cache Mode',
        description: 'Override the way the cache is used',
        type: SettingType.enumeration,
        defaultValue: CacheMode.LOAD_DEFAULT.toNativeValue(),
        enumValues: {
          'Default': CacheMode.LOAD_DEFAULT.toNativeValue(),
          'Cache Else Network': CacheMode.LOAD_CACHE_ELSE_NETWORK
              .toNativeValue(),
          'No Cache': CacheMode.LOAD_NO_CACHE.toNativeValue(),
          'Cache Only': CacheMode.LOAD_CACHE_ONLY.toNativeValue(),
        },
        property: InAppWebViewSettingsProperty.cacheMode,
      ),
    ],
    'Appearance': [
      SettingDefinition(
        key: 'transparentBackground',
        name: 'Transparent Background',
        description: 'Make the WebView background transparent',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.transparentBackground,
      ),
      SettingDefinition(
        key: 'verticalScrollBarEnabled',
        name: 'Vertical Scroll Bar',
        description: 'Show vertical scroll bar',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.verticalScrollBarEnabled,
      ),
      SettingDefinition(
        key: 'horizontalScrollBarEnabled',
        name: 'Horizontal Scroll Bar',
        description: 'Show horizontal scroll bar',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.horizontalScrollBarEnabled,
      ),
      SettingDefinition(
        key: 'scrollbarFadingEnabled',
        name: 'Scrollbar Fading',
        description: 'Fade scrollbars when not scrolling',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.scrollbarFadingEnabled,
      ),
      SettingDefinition(
        key: 'disableVerticalScroll',
        name: 'Disable Vertical Scroll',
        description: 'Disable vertical scrolling',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.disableVerticalScroll,
      ),
      SettingDefinition(
        key: 'disableHorizontalScroll',
        name: 'Disable Horizontal Scroll',
        description: 'Disable horizontal scrolling',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.disableHorizontalScroll,
      ),
      SettingDefinition(
        key: 'disableContextMenu',
        name: 'Disable Context Menu',
        description: 'Disable the long-press context menu',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.disableContextMenu,
      ),
    ],
    'Navigation': [
      SettingDefinition(
        key: 'allowsBackForwardNavigationGestures',
        name: 'Back/Forward Gestures',
        description: 'Enable swipe gestures for navigation',
        type: SettingType.boolean,
        defaultValue: true,
        property:
            InAppWebViewSettingsProperty.allowsBackForwardNavigationGestures,
      ),
    ],
    'Rendering': [
      SettingDefinition(
        key: 'suppressesIncrementalRendering',
        name: 'Suppress Incremental Rendering',
        description: 'Wait until content is fully loaded before rendering',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.suppressesIncrementalRendering,
      ),
      SettingDefinition(
        key: 'hardwareAcceleration',
        name: 'Hardware Acceleration',
        description: 'Enable hardware acceleration',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.hardwareAcceleration,
      ),
      SettingDefinition(
        key: 'useHybridComposition',
        name: 'Hybrid Composition',
        description: 'Use Flutter Hybrid Composition',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.useHybridComposition,
      ),
    ],
    'Zoom': [
      SettingDefinition(
        key: 'ignoresViewportScaleLimits',
        name: 'Ignore Viewport Scale Limits',
        description: 'Override user-scalable viewport setting',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.ignoresViewportScaleLimits,
      ),
      SettingDefinition(
        key: 'builtInZoomControls',
        name: 'Built-In Zoom Controls',
        description: 'Use built-in zoom controls',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.builtInZoomControls,
      ),
      SettingDefinition(
        key: 'displayZoomControls',
        name: 'Display Zoom Controls',
        description: 'Show on-screen zoom controls',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.displayZoomControls,
      ),
      SettingDefinition(
        key: 'pinchZoomEnabled',
        name: 'Pinch Zoom',
        description: 'Enable pinch-to-zoom gesture',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.pinchZoomEnabled,
      ),
    ],
    'Interaction': [
      SettingDefinition(
        key: 'allowsLinkPreview',
        name: 'Link Preview',
        description: 'Show link previews on long press',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.allowsLinkPreview,
      ),
    ],
    'Storage': [
      SettingDefinition(
        key: 'thirdPartyCookiesEnabled',
        name: 'Third-Party Cookies',
        description: 'Allow third-party cookies',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.thirdPartyCookiesEnabled,
      ),
      SettingDefinition(
        key: 'domStorageEnabled',
        name: 'DOM Storage',
        description: 'Enable DOM local storage',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.domStorageEnabled,
      ),
      SettingDefinition(
        key: 'databaseEnabled',
        name: 'Database',
        description: 'Enable database storage API',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.databaseEnabled,
      ),
    ],
    'APIs': [
      SettingDefinition(
        key: 'geolocationEnabled',
        name: 'Geolocation',
        description: 'Enable Geolocation API',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.geolocationEnabled,
      ),
    ],
    'Forms': [
      SettingDefinition(
        key: 'generalAutofillEnabled',
        name: 'General Autofill',
        description: 'Enable autofill for forms',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.generalAutofillEnabled,
      ),
      SettingDefinition(
        key: 'passwordAutosaveEnabled',
        name: 'Password Autosave',
        description: 'Enable password autosave',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.passwordAutosaveEnabled,
      ),
    ],
    'UI': [
      SettingDefinition(
        key: 'statusBarEnabled',
        name: 'Status Bar',
        description: 'Show status bar',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.statusBarEnabled,
      ),
      SettingDefinition(
        key: 'browserAcceleratorKeysEnabled',
        name: 'Browser Accelerator Keys',
        description: 'Enable browser keyboard shortcuts',
        type: SettingType.boolean,
        defaultValue: true,
        property: InAppWebViewSettingsProperty.browserAcceleratorKeysEnabled,
      ),
    ],
    'Developer': [
      SettingDefinition(
        key: 'isInspectable',
        name: 'Inspectable',
        description: 'Allow Web Inspector/DevTools',
        type: SettingType.boolean,
        defaultValue: false,
        property: InAppWebViewSettingsProperty.isInspectable,
      ),
    ],
  };
}
