import 'package:flutter_test/flutter_test.dart';

import 'audio_playback_policy.dart';
import 'content_blocker.dart';
import 'get_title.dart';
import 'http_auth_credential_database.dart';
import 'initial_url_request.dart';
import 'intercept_ajax_request.dart';
import 'intercept_fetch_request.dart';
import 'javascript_code_evaluation.dart';
import 'javascript_dialogs.dart';
import 'javascript_handler.dart';
import 'load_file_url.dart';
import 'load_url.dart';
import 'on_console_message.dart';
import 'on_download_start_request.dart';
import 'on_find_result_received.dart';
import 'on_js_before_unload.dart';
import 'on_load_error.dart';
import 'on_load_http_error.dart';
import 'on_load_resource.dart';
import 'on_load_resource_custom_scheme.dart';
import 'on_page_commit_visible.dart';
import 'on_permission_request.dart';
import 'on_print.dart';
import 'on_progress_changed.dart';
import 'on_received_icon.dart';
import 'on_received_touch_icon_url.dart';
import 'on_safe_browsing_hit.dart';
import 'on_scroll_changed.dart';
import 'on_title_changed.dart';
import 'on_update_visited_history.dart';
import 'on_window_blur.dart';
import 'on_window_focus.dart';
import 'on_zoom_scale_changed.dart';
import 'programmatic_scroll.dart';
import 'resize_webview.dart';
import 'set_custom_useragent.dart';
import 'set_get_settings.dart';
import 'should_intercept_request.dart';
import 'should_override_url_loading.dart';
import 'ssl_request.dart';
import 'video_playback_policy.dart';
import 'webview_windows.dart';

void main() {
  group('InAppWebView', () {
    initialUrlRequest();
    setGetSettings();
    javascriptCodeEvaluation();
    loadUrl();
    loadFileUrl();
    javascriptHandler();
    resizeWebView();
    setCustomUserAgent();
    videoPlaybackPolicy();
    audioPlaybackPolicy();
    getTitle();
    programmaticScroll();
    shouldOverrideUrlLoading();
    onLoadError();
    webViewWindows();
    interceptAjaxRequest();
    interceptFetchRequest();
    contentBlocker();
    httpAuthCredentialDatabase();
    onConsoleMessage();
    onFindResultReceived();
    onDownloadStartRequest();
    javascriptDialogs();
    onLoadHttpError();
    onLoadResourceCustomScheme();
    onLoadResource();
    onUpdateVisitedHistory();
    onProgressChanged();
    onSafeBrowsingHit();
    onScrollChanged();
    sslRequest();
    onPrint();
    onWindowFocus();
    onWindowBlur();
    onPageCommitVisible();
    onTitleChanged();
    onZoomScaleChanged();
    onPermissionRequest();
    shouldInterceptRequest();
    onReceivedIcon();
    onReceivedTouchIconUrl();
    onJsBeforeUnload();
  });
}